import type { DashboardLayout, CardType } from "@/types/dashboard"

export function getDefaultLayouts(): DashboardLayout[] {
  return [
    {
      id: "financial-template",
      name: "Financial Review Dashboard",
      description: "Comprehensive financial analytics and budget tracking",
      isTemplate: true,
      templateType: "financial",
      createdAt: new Date(),
      updatedAt: new Date(),
      cards: [
        {
          id: "financial-overview-1",
          type: "financial-overview",
          title: "Financial Overview",
          size: "large",
          position: { x: 0, y: 0 },
          visible: true,
          config: {},
        },
        {
          id: "budget-variance-1",
          type: "budget-variance",
          title: "Budget Variance",
          size: "medium",
          position: { x: 2, y: 0 },
          visible: true,
          config: {},
        },
        {
          id: "cash-flow-1",
          type: "cash-flow",
          title: "Cash Flow",
          size: "large",
          position: { x: 0, y: 1 },
          visible: true,
          config: {},
        },
        {
          id: "profitability-1",
          type: "profitability",
          title: "Profitability Analysis",
          size: "medium",
          position: { x: 2, y: 1 },
          visible: true,
          config: {},
        },
      ],
    },
    {
      id: "health-template",
      name: "Project Health Dashboard",
      description: "Monitor project health, risks, and quality metrics",
      isTemplate: true,
      templateType: "health",
      createdAt: new Date(),
      updatedAt: new Date(),
      cards: [
        {
          id: "health-overview-1",
          type: "health-overview",
          title: "Project Health Overview",
          size: "medium",
          position: { x: 0, y: 0 },
          visible: true,
          config: {},
        },
        {
          id: "risk-assessment-1",
          type: "risk-assessment",
          title: "Risk Assessment",
          size: "medium",
          position: { x: 1, y: 0 },
          visible: true,
          config: {},
        },
        {
          id: "quality-metrics-1",
          type: "quality-metrics",
          title: "Quality Metrics",
          size: "medium",
          position: { x: 2, y: 0 },
          visible: true,
          config: {},
        },
        {
          id: "safety-dashboard-1",
          type: "safety-dashboard",
          title: "Safety Dashboard",
          size: "medium",
          position: { x: 0, y: 1 },
          visible: true,
          config: {},
        },
        {
          id: "performance-score-1",
          type: "performance-score",
          title: "Performance Score",
          size: "small",
          position: { x: 1, y: 1 },
          visible: true,
          config: {},
        },
      ],
    },
    {
      id: "schedule-template",
      name: "Schedule Review Dashboard",
      description: "Track project schedules, milestones, and critical path",
      isTemplate: true,
      templateType: "schedule",
      createdAt: new Date(),
      updatedAt: new Date(),
      cards: [
        {
          id: "schedule-overview-1",
          type: "schedule-overview",
          title: "Schedule Overview",
          size: "large",
          position: { x: 0, y: 0 },
          visible: true,
          config: {},
        },
        {
          id: "milestone-tracker-1",
          type: "milestone-tracker",
          title: "Milestone Tracker",
          size: "medium",
          position: { x: 2, y: 0 },
          visible: true,
          config: {},
        },
        {
          id: "critical-path-1",
          type: "critical-path",
          title: "Critical Path Analysis",
          size: "large",
          position: { x: 0, y: 1 },
          visible: true,
          config: {},
        },
      ],
    },
  ]
}

export function getAvailableCardTypes(): CardType[] {
  return [
    {
      type: "financial-overview",
      title: "Financial Overview",
      description: "Revenue and cost tracking with trend analysis",
      category: "financial",
      defaultSize: "large",
      configurable: true,
    },
    {
      type: "budget-variance",
      title: "Budget Variance",
      description: "Track budget vs actual spending by project",
      category: "financial",
      defaultSize: "medium",
      configurable: true,
    },
    {
      type: "cash-flow",
      title: "Cash Flow",
      description: "Monitor cash inflows and outflows",
      category: "financial",
      defaultSize: "large",
      configurable: true,
    },
    {
      type: "profitability",
      title: "Profitability Analysis",
      description: "Project margin and profitability metrics",
      category: "financial",
      defaultSize: "medium",
      configurable: true,
    },
    {
      type: "health-overview",
      title: "Project Health",
      description: "Overall project health score and metrics",
      category: "health",
      defaultSize: "medium",
      configurable: true,
    },
    {
      type: "risk-assessment",
      title: "Risk Assessment",
      description: "Identify and track project risks",
      category: "health",
      defaultSize: "medium",
      configurable: true,
    },
    {
      type: "quality-metrics",
      title: "Quality Metrics",
      description: "Quality scores and inspection results",
      category: "health",
      defaultSize: "medium",
      configurable: true,
    },
    {
      type: "safety-dashboard",
      title: "Safety Dashboard",
      description: "Safety incidents and training metrics",
      category: "health",
      defaultSize: "medium",
      configurable: true,
    },
    {
      type: "schedule-overview",
      title: "Schedule Overview",
      description: "Project timeline and progress tracking",
      category: "schedule",
      defaultSize: "large",
      configurable: true,
    },
    {
      type: "milestone-tracker",
      title: "Milestone Tracker",
      description: "Upcoming milestones and deadlines",
      category: "schedule",
      defaultSize: "medium",
      configurable: true,
    },
    {
      type: "critical-path",
      title: "Critical Path",
      description: "Critical path analysis and task dependencies",
      category: "schedule",
      defaultSize: "large",
      configurable: true,
    },
    {
      type: "performance-score",
      title: "Performance Score",
      description: "Overall project performance rating",
      category: "performance",
      defaultSize: "small",
      configurable: false,
    },
  ]
}
